const rods = [
  ['Pinewhisper', 0, 8], ['Reedrunner', 90, 14], ['Tideglass', 220, 21], ['Saltwood', 430, 29], ['Moonline', 700, 38], ['Brinehook', 1050, 48], ['Deepcaller', 1500, 59], ['Stormcast', 2100, 71], ['Pearlspine', 2900, 84], ['Blackcurrent', 3900, 98], ['Leviathan', 5200, 113], ['Starbreaker', 6800, 129], ['Abyssal Reach', 8700, 146], ['Sovereign', 11000, 164], ['The Last Horizon', 14500, 185]
].map(([name, price, luck], index) => ({ name, price, luck, index }));
const baits = [
  ['Worms', 0, 0, 'A reliable classic'], ['Shimmer Grub', 30, 6, 'Catches curious fish'], ['Glow Squid', 85, 13, 'Bright in deep water'], ['Silver Minnow', 180, 22, 'A predator favourite'], ['Pearl Fly', 340, 32, 'Light as moon foam'], ['Ember Larva', 600, 44, 'Warm scent, rare pulls'], ['Abyssal Bloom', 950, 60, 'For the impossible catch']
].map(([name, price, luck, note], index) => ({ name, price, luck, note, index }));
const fish = [
  { name: 'Moonfin', emoji: '◒', value: 24, rarity: 'Common', minLuck: 0 }, { name: 'Glass Perch', emoji: '◈', value: 42, rarity: 'Common', minLuck: 5 }, { name: 'Lantern Eel', emoji: '≋', value: 70, rarity: 'Uncommon', minLuck: 15 }, { name: 'Kelpback', emoji: '◓', value: 96, rarity: 'Uncommon', minLuck: 25 }, { name: 'Coral Pike', emoji: '◁', value: 145, rarity: 'Rare', minLuck: 40 }, { name: 'Sapphire Ray', emoji: '◇', value: 210, rarity: 'Rare', minLuck: 55 }, { name: 'Sunken Koi', emoji: '◉', value: 300, rarity: 'Epic', minLuck: 75 }, { name: 'Starlit Marlin', emoji: '✦', value: 460, rarity: 'Legendary', minLuck: 100 }
];
const state = { coins: 120, rod: 0, bait: 0, ownedRods: new Set([0]), ownedBaits: new Set([0]), haul: [], collection: {}, fishing: false, biteTimer: null, sound: true };
const $ = (id) => document.getElementById(id);
const totalLuck = () => rods[state.rod].luck + baits[state.bait].luck;
function updateHud() { $('coins').textContent = state.coins.toLocaleString(); $('equipped-rod').textContent = rods[state.rod].name; $('equipped-bait').textContent = baits[state.bait].name; $('luck-value').textContent = `+${totalLuck()}%`; $('haul-count').textContent = state.haul.length; $('haul-count').style.display = state.haul.length ? 'block' : 'none'; }
function toast(message) { const el = $('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 2300); }
function catchToast(caught) { const el = $('catch-toast'); el.innerHTML = `<span>${caught.emoji}  ${caught.name} caught!</span><small>${caught.rarity} catch • worth ${caught.value} coins</small>`; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 3000); }
function chooseFish() { const luck = totalLuck(); const eligible = fish.filter(item => luck >= item.minLuck); const weighted = eligible.flatMap(item => Array(Math.max(1, 110 - item.minLuck + luck / 2)).fill(item)); return weighted[Math.floor(Math.random() * weighted.length)]; }
function startFishing() { if (state.fishing) { if ($('bite-alert').classList.contains('visible')) reelIn(); else toast('Your line is already in the water.'); return; } state.fishing = true; $('cast-button').disabled = true; $('cast-button').innerHTML = '<span class="cast-icon">⌁</span><strong>WAITING...</strong><small>LISTEN CLOSELY</small>'; $('action-copy').textContent = 'The tide is moving. Watch for the tug.'; const wait = 1700 + Math.random() * 2600 - Math.min(totalLuck() * 9, 900); state.biteTimer = setTimeout(() => { $('bite-alert').classList.add('visible'); $('action-copy').textContent = 'A fish is on! Reel it in now.'; $('cast-button').disabled = false; $('cast-button').innerHTML = '<span class="cast-icon">↟</span><strong>REEL IN</strong><small>SPACE</small>'; state.biteTimer = setTimeout(() => { if (state.fishing) missFish(); }, 4200); }, Math.max(800, wait)); }
function missFish() { clearTimeout(state.biteTimer); state.fishing = false; $('bite-alert').classList.remove('visible'); $('cast-button').disabled = false; $('cast-button').innerHTML = '<span class="cast-icon">⌁</span><strong>CAST LINE</strong><small>SPACE</small>'; $('action-copy').textContent = 'The fish slipped away. Try another cast.'; toast('The fish got away.'); }
function reelIn() { clearTimeout(state.biteTimer); const caught = chooseFish(); state.haul.push(caught); state.collection[caught.name] = (state.collection[caught.name] || 0) + 1; state.fishing = false; $('bite-alert').classList.remove('visible'); $('cast-button').disabled = false; $('cast-button').innerHTML = '<span class="cast-icon">⌁</span><strong>CAST LINE</strong><small>SPACE</small>'; $('action-copy').textContent = 'Nice catch. Sell it or cast again.'; updateHud(); catchToast(caught); }
function openPanel(panel) { const backdrop = $('modal-backdrop'); const modal = $('panel-modal'); document.querySelectorAll('.rail-button[data-panel]').forEach(button => button.classList.toggle('active', button.dataset.panel === panel)); if (panel === 'play') { closePanel(); return; } backdrop.hidden = false; modal.innerHTML = panelMarkup(panel); modal.querySelector('.close-panel').addEventListener('click', closePanel); if (panel === 'shop') { modal.querySelectorAll('.shop-tab').forEach(tab => tab.addEventListener('click', () => { modal.querySelectorAll('.shop-tab').forEach(x => x.classList.remove('active')); tab.classList.add('active'); modal.querySelector('.catalog').innerHTML = catalogMarkup(tab.dataset.catalog); bindCatalog(modal); })); bindCatalog(modal); } if (panel === 'sell') bindSell(modal); }
function closePanel() { $('modal-backdrop').hidden = true; }
function panelMarkup(panel) { if (panel === 'shop') return `<div class="panel-head"><div><h2>Outfitter</h2><p>Fine-tune your luck before the next cast.</p></div><button class="close-panel">×</button></div><div class="shop-tabs"><button class="shop-tab active" data-catalog="rods">RODS <span>15</span></button><button class="shop-tab" data-catalog="baits">BAIT <span>7</span></button></div><div class="catalog">${catalogMarkup('rods')}</div>`; if (panel === 'sell') return `<div class="panel-head"><div><h2>Fish market</h2><p>Turn your haul into coin for better gear.</p></div><button class="close-panel">×</button></div><div class="sell-content">${sellMarkup()}</div>`; if (panel === 'collection') return `<div class="panel-head"><div><h2>Field collection</h2><p>Every species you land is logged here.</p></div><button class="close-panel">×</button></div><div class="collection-content">${collectionMarkup()}</div>`; return `<div class="panel-head"><div><h2>How to fish</h2><p>Three small moves, a whole ocean of possibilities.</p></div><button class="close-panel">×</button></div><div class="help-copy"><strong>1. Cast your line</strong><br>Press <kbd>SPACE</kbd> or click CAST LINE. <br><br><strong>2. Listen for the tug</strong><br>When the bite alert appears, press <kbd>SPACE</kbd> again to reel in. Your rod and bait luck influence which fish notice you.<br><br><strong>3. Build your kit</strong><br>Sell your haul at the market, then spend coins on rods and bait. Each catalog has its own luck curve, and the collection remembers every species you discover.</div>`; }
function catalogMarkup(type) { const items = type === 'rods' ? rods : baits; const owned = type === 'rods' ? state.ownedRods : state.ownedBaits; return items.map(item => { const isOwned = owned.has(item.index); const isEquipped = (type === 'rods' ? state.rod : state.bait) === item.index; return `<article class="item-card ${isEquipped ? 'equipped' : ''}"><h3>${item.name}</h3><p>${type === 'rods' ? `Precision ${item.index + 1} · ${item.luck}% base luck` : item.note}</p><span class="item-price">${item.price ? `◆ ${item.price.toLocaleString()}` : 'STARTER'}</span><span class="luck-pill">+${item.luck}% luck</span><button class="buy-button" data-type="${type}" data-index="${item.index}" ${!isOwned && state.coins < item.price ? 'disabled' : ''}>${isEquipped ? 'EQUIPPED' : isOwned ? 'EQUIP' : 'BUY'}</button></article>`; }).join(''); }
function bindCatalog(modal) { modal.querySelectorAll('.buy-button').forEach(button => button.addEventListener('click', () => { const type = button.dataset.type; const index = Number(button.dataset.index); const owned = type === 'rods' ? state.ownedRods : state.ownedBaits; const item = (type === 'rods' ? rods : baits)[index]; if (!owned.has(index)) { if (state.coins < item.price) return toast('You need more coins for that.'); state.coins -= item.price; owned.add(index); toast(`${item.name} added to your kit.`); } if (type === 'rods') state.rod = index; else state.bait = index; updateHud(); openPanel('shop'); setTimeout(() => { const tab = document.querySelector(`[data-catalog="${type}"]`); if (tab) tab.click(); }, 0); })); }
function sellMarkup() { if (!state.haul.length) return '<div class="empty-state">Your creel is empty.<br>Cast a line and bring something back.</div>'; return `${state.haul.map((item, index) => `<div class="haul-row"><span class="fish-emoji">${item.emoji}</span><div><h3>${item.name}</h3><small>${item.rarity} catch</small></div><span class="row-value">◆ ${item.value}</span><button class="sell-one" data-index="${index}">SELL</button></div>`).join('')}<button class="sell-all">SELL ALL · ◆ ${state.haul.reduce((sum, item) => sum + item.value, 0)}</button>`; }
function bindSell(modal) { modal.querySelectorAll('.sell-one').forEach(button => button.addEventListener('click', () => { const [sold] = state.haul.splice(Number(button.dataset.index), 1); state.coins += sold.value; updateHud(); toast(`Sold ${sold.name} for ${sold.value} coins.`); openPanel('sell'); })); const sellAll = modal.querySelector('.sell-all'); if (sellAll) sellAll.addEventListener('click', () => { const value = state.haul.reduce((sum, item) => sum + item.value, 0); state.haul = []; state.coins += value; updateHud(); toast(`Haul sold for ${value} coins.`); openPanel('sell'); }); }
function collectionMarkup() { const found = Object.keys(state.collection).length; return `<div class="collection-progress"><span>${found} / ${fish.length} SPECIES DISCOVERED</span><span>${state.haul.length} IN CREEL</span></div><div class="progress-bar"><i style="width:${found / fish.length * 100}%"></i></div><div class="collection-grid">${fish.map(item => { const count = state.collection[item.name] || 0; return `<div class="fish-entry ${count ? '' : 'locked'}"><span class="count">${count ? `×${count}` : '—'}</span><div class="fish-emoji">${count ? item.emoji : '?'}</div><h3>${count ? item.name : 'Undiscovered'}</h3><small>${count ? item.rarity : `Luck ${item.minLuck}%+`}</small></div>`; }).join('')}</div>`; }
document.querySelectorAll('[data-panel]').forEach(button => button.addEventListener('click', () => openPanel(button.dataset.panel))); $('cast-button').addEventListener('click', startFishing); $('modal-backdrop').addEventListener('click', event => { if (event.target.id === 'modal-backdrop') closePanel(); }); $('help-button').addEventListener('click', () => openPanel('help')); $('sound-toggle').addEventListener('click', () => { state.sound = !state.sound; $('sound-toggle').textContent = state.sound ? '◖' : '—'; }); document.addEventListener('keydown', event => { const keybinds = window.getTheFisherKeybinds ? window.getTheFisherKeybinds() : { action: 'Space', close: 'Escape' }; if (event.code === keybinds.action && !$('modal-backdrop').hidden) return; if (event.code === keybinds.action) { event.preventDefault(); startFishing(); } if (event.code === keybinds.close) closePanel(); }); updateHud();

const gameView = document.querySelector('.game-view');
let lookX = 0;
let lookY = 0;
let draggingLook = false;
function updateLook() { document.documentElement.style.setProperty('--look-x', lookX); document.documentElement.style.setProperty('--look-y', lookY); }
gameView.addEventListener('click', event => { if (event.target.closest('button') || !document.pointerLockElement) return; });
gameView.addEventListener('mousedown', event => { if (event.target.closest('button') || !$('modal-backdrop').hidden) return; draggingLook = true; gameView.classList.add('is-looking'); if (gameView.requestPointerLock) gameView.requestPointerLock(); });
document.addEventListener('mouseup', () => { draggingLook = false; if (!document.pointerLockElement) gameView.classList.remove('is-looking'); });
document.addEventListener('pointerlockchange', () => { gameView.classList.toggle('is-looking', document.pointerLockElement === gameView); });
document.addEventListener('mousemove', event => { if (document.pointerLockElement !== gameView && !draggingLook) return; lookX = Math.max(-115, Math.min(115, lookX + event.movementX * 0.24)); lookY = Math.max(-72, Math.min(72, lookY + event.movementY * 0.18)); updateLook(); });
const catchEffectObserver = new MutationObserver(() => { if (!$('catch-toast').classList.contains('show')) return; gameView.classList.remove('catching'); void gameView.offsetWidth; gameView.classList.add('catching'); setTimeout(() => gameView.classList.remove('catching'), 850); });
catchEffectObserver.observe($('catch-toast'), { attributes: true, attributeFilter: ['class'] });
